version: '3.8'

services:
  backend: 
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/backend/project/static
      - media_volume:/home/app/backend/project/media
    expose:
      - 1341:5000
    env_file:
      - ./.env.prod
      - ./.env
    depends_on:
      - postgres
      
  postgres:
    build: services/postgres
    volumes:
      - ./:/tmp/db
      - postgres_data_prod:/var/lib/postgresql/data/
    ports: ["12346:5432"]
    env_file:
      - ./.env.prod.db
  
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod  # Use a Dockerfile specific to production
    volumes:
      - static_volume:/usr/share/nginx/html
      - static_volume:/home/app/backend/project/static  # Copy build output to static folder  
    env_file:        
      - ./.env.prod
    depends_on:
      - backend

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/usr/share/nginx/html  # Mount build output here
      - static_volume:/home/app/backend/project/static
      - media_volume:/home/app/backend/project/media
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: